### ISSUE TITLE
这个工具似乎在 macOS 下无法正常工作？

### ISSUE THREAD

**Issue by womeimingzi11** [mobier/shadowsocksr-speed#1]
macOS 下似乎没有 xvfb，之后使用 Brew cask 安装chromedriver。

运行脚本后，提示输入 url，按提示输入后显示完 ipv6 not support 之后就没有下一步的进度了

等待了半小时左右后，使用 ctrl+c 停止进程，可以显示节点名并有一系列错误提醒后，退出进程。

查看网络连接，Python 只有获取节点这一步的网络流量。

**Comment by mobier** [comment]
可以提供一下错误信息吗？我明天找台mac试试

**Comment by womeimingzi11** [comment]
这是 Terminal 中会卡顿的位置
![1](https://user-images.githubusercontent.com/10340253/47716188-e02e8280-dc7c-11e8-903b-411b752f92b3.jpg)

这是 Surge 显示的网络连接状况
![8](https://user-images.githubusercontent.com/10340253/47716256-208e0080-dc7d-11e8-93f1-f4dbeede21f0.jpg)

使用 Ctrl + C 中止进程，提醒信息如下：

IPv6 not support
^CIPv6 not support
^C----------------------------
上海阿里云(倍率:1)/139.196.82.179
ping_local
HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: http://api.ip.sb/ip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104542898>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [Errno 61] Connection refused',)))
IPv6 not support
^CIPv6 not support
^C----------------------------
上海阿里云2(倍率:1)/47.101.42.188
ping_local
HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: http://api.ip.sb/ip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104558048>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [Errno 61] Connection refused',)))
IPv6 not support
^CIPv6 not support
^C----------------------------
伦敦AWS(倍率:0.6)/lon.aws.ccddns.online
ping_local
HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: http://api.ip.sb/ip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104558780>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [Errno 61] Connection refused',)))
IPv6 not support
^CIPv6 not support
^C----------------------------
伦敦DO(倍率:0.5)/lon.do.ccddns.online
ping_local
HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: http://api.ip.sb/ip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104558eb8>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [Errno 61] Connection refused',)))
IPv6 not support
^CIPv6 not support
^C----------------------------
俄罗斯伯力(倍率:0.8)/92.38.128.143
^CTraceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/socks.py", line 832, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/socks.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/socks.py", line 844, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/local/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x104558ef0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/anaconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: http://api.ip.sb/ip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104558ef0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [Errno 61] Connection refused',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "shadowsocksr-speed.py", line 40, in connect_ssr
    ip=requests.get('http://api.ip.sb/ip',timeout=15).text
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPConnectionPool(host='127.0.0.1', port=8888): Max retries exceeded with url: http://api.ip.sb/ip (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104558ef0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [Errno 61] Connection refused',)))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "shadowsocksr-speed.py", line 122, in <module>
    speed_result.append(connect_ssr(s))#通过解析后的配置信息链接节点进行测速
  File "shadowsocksr-speed.py", line 98, in connect_ssr
    ping_pc=os.popen(cmd).readlines()#.strip()
KeyboardInterrupt

**Comment by womeimingzi11** [comment]
我尝试关掉了代理软件（Surge），把默认端口指定了 443，貌似可以运行了（不过因为节点多，节点稳定性也不保证，测试还在进行中）

**Comment by womeimingzi11** [comment]
不过顺便也想起来一个问题，是否有可能增加一个手动选择测速节点的功能？因为有些节点，完全不打算测速，却也要花时间进行，影响测试效率

**Comment by mobier** [comment]
OK，估计是代理开了全局的缘故，手动选择节点我后面加上去
