### ISSUE TITLE
MAC 报错IPv6 not support，结果都是0，network:Fail

### ISSUE THREAD

**Issue by chc880** [mobier/shadowsocksr-speed#29]

**Comment by mobier** [comment]
可以发我一下订阅链接吗?vxxwej@gmail.com

**Comment by neighbor007** [comment]
mac端报错，我少什么东西嘛，大佬帮忙看下
IPv6` not support
2019-06-05 23:55:12 ERROR    shell.py:50 [Errno 2] No such file or directory: '/var/run/shadowsocksr.pid'
2019-06-05 23:55:12 ERROR    daemon.py:146 not running
IPv6 not support
Traceback (most recent call last):
  File "shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/Users/zander/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/Users/zander/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/Users/zander/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/Users/zander/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/Users/zander/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/Users/zander/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/Users/zander/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
[VIP-2]-香港-6-视频节点-1Gbps-1.0倍	 - 989 端口单端口多用户/hk6.vip.mz-ssr.com
<urlopen error Error connecting to SOCKS5 proxy 127.0.0.1:6667: [Errno 61] Connection refused>
