### ISSUE TITLE
无法找到 chromedriver

### ISSUE THREAD

**Issue by LansirLan** [mobier/shadowsocksr-speed#54]
运行 youtube 测试时发现全部为 0， 跑 test.py 提示找不到 chromedriver。
但是实际是加入了 /usr/bin 目录中
terminal 直接运行 chromedriver 命令能成功。
报错如下：

```
xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!
Message: unknown error: cannot find Chrome binary

Traceback (most recent call last):
  File "/home/zhiquan/shadowsocksr-speed/youtube_speed.py", line 72, in test_speed
    browser = webdriver.Chrome(executable_path='/usr/bin/chromedriver', chrome_options = chromeOptions)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 53, in <module>
    youtube_speed.test_speed("1080")
  File "/home/zhiquan/shadowsocksr-speed/youtube_speed.py", line 158, in test_speed
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
```

**Comment by mobier** [comment]
加一行chromeOptions.binary_location=r'/usr/bin/chromedriver' 试试。或者看看是不是sudo权限的问题

**Comment by LansirLan** [comment]
加了 binary_location 貌似能正确找到了， 但是又有新的异常跑出， 如下：

```
zhiquan@ubuntu:~/shadowsocksr-speed$ sudo python3 test.py
xdpyinfo was not found, X start can not be checked! Please install xdpyinfo!
Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromedriver is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

Traceback (most recent call last):
  File "/home/zhiquan/shadowsocksr-speed/youtube_speed.py", line 73, in test_speed
    browser = webdriver.Chrome(chrome_options = chromeOptions)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/zhiquan/.local/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromedriver is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
```

搜了一下说得加 `--no-sandbox` 但是我看你有加过。
你有没有遇到过

**Comment by mobier** [comment]
你试试~我记得当时加了这个参数有问题来着

**Comment by LansirLan** [comment]
翻看 Chromedriver 文档，发现apt完整安装,  问题可以解决, 
且不用指定 binary_location， 供参考：
`sudo apt-get install chromium-chromedriver`

- ubuntu 19.04
- python3.7
