### ISSUE TITLE
Linux下使用报错,另一个机场可以正常使用

### ISSUE THREAD

**Issue by Biggulu** [mobier/shadowsocksr-speed#6]
sudo python3 shadowsocksr-speed.py
url:https://***************0
Traceback (most recent call last):
  File "shadowsocksr-speed.py", line 317, in <module>
    ssr_config.append(ParseSsr.parse(decdata))#解析"SSR://" 后边的base64的配置信息返回一个字典
  File "/home/adam/ssr-speedtest/ParseSsr.py", line 22, in parse
    return parse_ssr(base64_encode_str)
  File "/home/adam/ssr-speedtest/ParseSsr.py", line 90, in parse_ssr
    password = base64_decode(password_encode_str)
  File "/home/adam/ssr-speedtest/ParseSsr.py", line 12, in base64_decode
    return base64.urlsafe_b64decode(base64_encode_str).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 3: invalid start byte

**Comment by mobier** [comment]
提供的是普通/433端口的订阅链接吗?用浏览器访问一下看看是否能获取到数据
