### ISSUE TITLE
ModuleNotFoundError: No module named 'pyvirtualdisplay'

### ISSUE THREAD

**Issue by shslave** [mobier/shadowsocksr-speed#62]
```
$ sudo python3 shadowsocksr-speed.py
Traceback (most recent call last):
  File "shadowsocksr-speed.py", line 9, in <module>
    import youtube_speed
  File "shadowsocksr-speed/youtube_speed.py", line 4, in <module>
    from pyvirtualdisplay import Display
ModuleNotFoundError: No module named 'pyvirtualdisplay'

$ pip install pyvirtualdisplay
Requirement already satisfied: pyvirtualdisplay in miniconda3/lib/python3.7/site-packages (0.2.4)

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

$ python -V
Python 3.7.4

$ pip -V
pip 19.2.2 from miniconda3/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by mobier** [comment]
sudo pip install pyvirtualdisplay
