### ISSUE TITLE
win下报错

### ISSUE THREAD

**Issue by jinjfykyc** [mobier/shadowsocksr-speed#63]
PS C:\Users\1101\Desktop\shadowsocksr-speed-master> python shadowsocksr-speed_win.py gui-config.json
gui-config.json
Traceback (most recent call last):
  File "shadowsocksr-speed_win.py", line 164, in <module>
    file_config=json.load(f)
  File "C:\Users\1101\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\1101\AppData\Local\Programs\Python\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 99384: invalid continuation byte

**Comment by jinjfykyc** [comment]
第一次运行正常，第二次没有运行完直接关了cmd，再次运行报销如上。

**Comment by mobier** [comment]
试试替换[gui-config.json](https://github.com/mobier/shadowsocksr-speed/blob/master/win/gui-config.json) 文件

**Comment by jinjfykyc** [comment]
换了后正常了。谢谢提醒。
