### ISSUE TITLE
windows 运行问题，求教

### ISSUE THREAD

**Issue by snjps007** [mobier/shadowsocksr-speed#64]
Traceback (most recent call last):
  File "shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "shadowsocksr/shadowsocks/local.py", line 48, in main
    daemon.daemon_exec(config)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\daemon.py", line 34, in daemon_exec
    raise Exception('daemon mode is only supported on Unix')
Exception: daemon mode is only supported on Unix
Traceback (most recent call last):
  File "shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 89, in __init__
    load_openssl()
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 41, in load_openssl
    raise Exception('libcrypto(OpenSSL) not found')
Exception: libcrypto(OpenSSL) not found
香港-HKT-hkbn - 31546 单端口/hk-hkbn-01.lonelylink.ltd
'grep' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
ping_test,localPing: []
HTTPConnectionPool(host='api.ip.sb', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202DFA866A0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
+-------------------------------------------+----+-----------+------+--------+----------+---------+---------+
|                    name                   | ip | localPing | ping | upload | download | youtube | network |
+-------------------------------------------+----+-----------+------+--------+----------+---------+---------+
|        香港-HKT-hkbn - 31546 单端口       |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|          韩国 AWS - 31546 单端口          |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|     美国Ultra-1G-支持NF - 31546 单端口    |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
| 美国 -安畅GIA 支持Nf-1000m - 31546 单端口 |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|         测试单端口 - 31546 单端口         |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|          日本 AWS1 - 31546 单端口         |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|  日本 -专线优化1GB-支持NF - 31546 单端口  |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|      新加坡-单端口测试 - 31546 单端口     |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|         新加坡 AWS2 - 31546 单端口        |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|         新加坡 AWS1 - 31546 单端口        |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|       新加坡 -Alcloud - 31546 单端口      |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|   台湾Hinet-支持NF-600M+ - 31546 单端口   |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
|  俄罗斯 -北方联通电信首选 - 31546 单端口  |    |     []    |  0   |   0    |    0     |    0    |   Fail  |
+-------------------------------------------+----+-----------+------+--------+----------+---------+---------+
Traceback (most recent call last):
  File "shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "shadowsocksr/shadowsocks/local.py", line 48, in main
    daemon.daemon_exec(config)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\daemon.py", line 34, in daemon_exec
    raise Exception('daemon mode is only supported on Unix')
Exception: daemon mode is only supported on Unix
Traceback (most recent call last):
  File "shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 299, in get_config
    check_config(config, is_local)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 89, in __init__
    load_openssl()
  File "D:\shadowsocksr-speed-master\shadowsocksr\shadowsocks\..\shadowsocks\crypto\openssl.py", line 41, in load_openssl
    raise Exception('libcrypto(OpenSSL) not found')
Exception: libcrypto(OpenSSL) not found
香港-HKT打机线-1000m-支持NF - 31546 单端口/hkt-cnb.mailgung.ml
'grep' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
ping_test,localPing: []
HTTPConnectionPool(host='api.ip.sb', port=80): Max retries exceeded with url: /ip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000202DFA8E8D0>: Failed to establish a new connection: Error connecting to SOCKS5 proxy 127.0.0.1:6667: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

两个报错
'grep' 不是内部或外部命令，也不是可运行的程序或批处理文件。
WinError 10061] 由于目标计算机积极拒绝，无法连接。

实际应该是连通可测  结果都是红色fail

**Comment by mobier** [comment]
Windows 用户
python shadowsocksr-speed_win.py
url: //输入入SSR订阅链接

**Comment by snjps007** [comment]
用老大的方法测试可行
谢谢

我以前用的是
shadowsocksr-speed_win.py
url: //输入入SSR订阅链接
会报'grep' 不是内部或外部命令，也不是可运行的程序或批处理文件。
WinError 10061] 由于目标计算机积极拒绝，无法连接。

老大用的python shadowsocksr-speed_win.py

python shadowsocksr-speed_win.py和shadowsocksr-speed_win.py  有什么区别，请教

**Comment by zfk513** [comment]
> 用老大的方法测试可行
> 谢谢
> 
> 我以前用的是
> shadowsocksr-speed_win.py
> url: //输入入SSR订阅链接
> 会报'grep' 不是内部或外部命令，也不是可运行的程序或批处理文件。
> WinError 10061] 由于目标计算机积极拒绝，无法连接。
> 
> 老大用的python shadowsocksr-speed_win.py
> 
> python shadowsocksr-speed_win.py和shadowsocksr-speed_win.py 有什么区别，请教

加python 是用python在cmd里面打开显示,不然就是直接打开文件(和双击打开的效果一样),弹窗pythonGUI打开
