### ISSUE TITLE
prettytable死活安装不了

### ISSUE THREAD

**Issue by waiaan** [mobier/shadowsocksr-speed#68]
用pip install报错：

    ERROR: Command errored out with exit status 1:
     command: 'h:\softwares\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-_j01yyjl\\prettytable\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-_j01yyjl\\prettytable\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-_j01yyjl\prettytable\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-_j01yyjl\prettytable\setup.py", line 3, in <module>
        from prettytable import __version__ as version
    ModuleNotFoundError: No module named 'prettytable'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

将prettytable包下载后手动安装也报错：

 ERROR: Command errored out with exit status 1:
     command: 'h:\softwares\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-0pital7a\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-req-build-0pital7a\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-0pital7a\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-req-build-0pital7a\setup.py", line 3, in <module>
        from prettytable import __version__ as version
    ModuleNotFoundError: No module named 'prettytable'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

求指点，谢谢！

**Comment by waiaan** [comment]
已解决，重装了python。
