### ISSUE TITLE
Exception: libsodium not found & IPv6 not support

### ISSUE THREAD

**Issue by keitpyocshe** [mobier/shadowsocksr-speed#69]
Hi, here. I got the error below, anyone any ideas to deal this?

```
IPv6 not support
2019-09-21 11:15:18 ERROR    daemon.py:141 not running
Traceback (most recent call last):
  File "shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "shadowsocksr/shadowsocks/local.py", line 48, in main
    daemon.daemon_exec(config)
  File "/Users/sssss/repo/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/daemon.py", line 43, in daemon_exec
    daemon_stop(pid_file)
  File "/Users/sssss/repo/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/daemon.py", line 149, in daemon_stop
    pid = int(pid)
ValueError: invalid literal for int() with base 10: ''
IPv6 not support
Traceback (most recent call last):
  File "shadowsocksr/shadowsocks/local.py", line 81, in <module>
    main()
  File "shadowsocksr/shadowsocks/local.py", line 43, in main
    config = shell.get_config(True)
  File "/Users/sssss/repo/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/Users/sssss/repo/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/Users/sssss/repo/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/Users/sssss/repo/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/Users/sssss/repo/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/Users/sssss/repo/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/Users/sssss/repo/shadowsocksr-speed/shadowsocksr/shadowsocks/../shadowsocks/crypto/sodium.py", line 42, in load_libsodium
    raise Exception('libsodium not found')
Exception: libsodium not found
```

**Comment by zhEdward** [comment]
> libsodium not found 

install manual,e.g. `# brew install libsodium` 

>IPv6 not support

see https://github.com/mobier/shadowsocksr-speed/issues/42#issuecomment-509128010
