### ISSUE TITLE
错误报告

### ISSUE THREAD

**Issue by Heavensward** [mobier/shadowsocksr-speed#82]
```
Traceback (most recent call last):
    File "shadowsocksr-speed_win.py", line 186, in <module>
        write_json(x)
    File "shadowsocksr-speed_win.py", line 134, in write_json
        if 'protoparam' in json_config['configs'][0]:
TypeError: argument of type 'NoneType' is not iterable
```

测速测到一半停止了，错误信息在上面。

**Comment by smithereensarr** [comment]
> ```
> Traceback (most recent call last):
>     File "shadowsocksr-speed_win.py", line 186, in <module>
>         write_json(x)
>     File "shadowsocksr-speed_win.py", line 134, in write_json
>         if 'protoparam' in json_config['configs'][0]:
> TypeError: argument of type 'NoneType' is not iterable
> ```
> 
> 测速测到一半停止了，错误信息在上面。

同样的问题，日志相同 http的订阅地址
