### ISSUE TITLE
输入订阅地址后，无法解析

### ISSUE THREAD

**Issue by GuardMY** [mobier/shadowsocksr-speed#94]
不能解析SSR链接: 
不能解析SSR链接: 
Traceback (most recent call last):
  File "shadowsocksr-speed.py", line 327, in <module>
    ssr_config=curses.wrapper(SelectTable)
  File "/usr/lib/python3.6/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "shadowsocksr-speed.py", line 158, in SelectTable
    x['select']=1
TypeError: 'NoneType' object does not support item assignment

**Comment by irezm** [comment]
同样的问题

**Comment by irezm** [comment]
➜  shadowsocksr-speed git:(master) python3 shadowsocksr-speed.py
url:https://losadhwselfff2332dasd.xyz/link/yS1OCia3k6YYO34x?mu=0
不能解析SSR链接: MjQwMDo4NTAwOjE4MDE6NDE1OjExOD2oyNzozMDoyMDU6NTIxNDE6b3JpZ2luOnJjNC1tZDU6xHR0cF9zaW1wbGU6TlV4dlpHWkQvP29iZnNwYXJhbT1aRzkzYm14dllXUXVkMmx1W4c5M2MzVndaR0YwWlM1amIyMCZwcm90b3BhcmFtPSZyZW1hcmtzPTVwZWw1cHlzSUdsd2RqWWdU0F6UjJKd2N5QXg1WUNOJmdyb3VwPWMzTnlZMnh2ZFdR
Traceback (most recent call last):
  File "shadowsocksr-speed.py", line 327, in <module>
    ssr_config=curses.wrapper(SelectTable)
  File "/usr/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "shadowsocksr-speed.py", line 158, in SelectTable
    x['select']=1
TypeError: 'NoneType' object does not support item assignment

**Comment by irezm** [comment]
➜  shadowsocksr-speed git:(master) python3 shadowsocksr-speed.py
url:https://losaxhgselfff2158dasd.xyz/link/y51TCis0k2YXO3sx?mu=0
不能解析SSR链接: MjQwMDo4NTAwOjE4MDE6NDE1OjExODoyNzozMDbyMDU6NTIxNSE6b3JpZ2luOnJjNC1tZDU6aHR0cF9zaW1wbGU6TlV4dlpHWkQvP29iZnNwYXJhbT1aRzkzYm14dllXUXVaMmx1Wkc5M2MzVndaR0YwWlM1amIyMCZwcm90b3BhcmFtPSZyZW1hcmtzPTVwZWw1cHlzSUdsd2RqWWdRU0F6UjJKt2N5QXj1WUNOJmdyb3VwPWMzTnlZMnh2ZFdR
Traceback (most recent call last):
  File "shadowsocksr-speed.py", line 327, in <module>
    ssr_config=curses.wrapper(SelectTable)
  File "/usr/lib/python3.7/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "shadowsocksr-speed.py", line 158, in SelectTable
    x['select']=1
TypeError: 'NoneType' object does not support item assignment
